#!/bin/sh

stop_run()
{
        killall -9 newplayrobot.py
        exit 0
}

trap "stop_run" SIGINT



export LD_LIBRARY_PATH=../xlib/:.

ulimit -n 4096
ulimit -c unlimited



for i in `seq 50`
do
	./newplayrobot.py ${i} >&${i}.log &
	sleep 0.1
done



while true
do
        sleep 1
done



